/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package plethoraquoteproducer;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Arc2D;
import java.awt.geom.Line2D;
import java.util.ArrayList;
import javafx.util.Pair;

/**
 * 
 * @author mewer
 */
public class ImagePanel extends javax.swing.JPanel {

    /**
     * Creates new form ImagePanel
     */
    public ImagePanel() {
      initComponents();
    }

    private ArrayList<Pair<Profile, Color>> profiles = new ArrayList<Pair<Profile, Color>>();
    
    public void addProfile(Profile profile, Color color) {
      profiles.add(new Pair<Profile, Color>(profile, color));
      this.invalidate();
      this.repaint();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
      super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
      Graphics2D g2 = (Graphics2D)g;
      for (Pair<Profile, Color> pair : profiles) {
        Profile profile = pair.getKey();
        Color color = pair.getValue();
        g2.setColor(color);
        for (Line2D line : profile.lines) {
          g2.draw(line);
        }
        for (Arc arc : profile.arcs) {
          //TODO Kinda inefficient
          Arc2D arc2d = new Arc2D.Double(arc.center.getX() - arc.radius, arc.center.getY() + arc.radius, 2 * arc.radius, 2 * arc.radius, arc.startAngle, Utils.mod(arc.endAngle - arc.startAngle, 2 * Math.PI), Arc2D.OPEN);
          g2.draw(arc2d);
        }
      }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(0, 300, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
